name: mySoTTA
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - blessed=1.20.0=py312h06a4308_0
  - brotli-python=1.0.9=py312h6a678d5_9
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.2.25=h06a4308_0
  - contourpy=1.3.1=py312hdb19cb5_0
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - expat=2.7.1=h6a678d5_0
  - fontconfig=2.14.1=h55d465d_3
  - fonttools=4.55.3=py312h5eee18b_0
  - freetype=2.13.3=h4a9f257_0
  - gpustat=1.1.1=py312h06a4308_0
  - icu=73.1=h6a678d5_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - joblib=1.4.2=py312h06a4308_0
  - jpeg=9e=h5eee18b_3
  - kiwisolver=1.4.8=py312h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20250127.0=cxx17_h6a678d5_0
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.9.1.3=0
  - libcups=2.4.2=h2d74bed_1
  - libcurand=10.3.5.147=0
  - libcurl=8.12.1=hc9e6f67_0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libdeflate=1.22=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.84.2=h37c7471_0
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libnghttp2=1.57.0=h2d74bed_0
  - libnpp=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libpng=1.6.39=h5eee18b_0
  - libpq=17.4=hdbd6064_0
  - libprotobuf=5.29.3=h3cdef7c_1
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.7.0=hde9077f_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libxkbcommon=1.9.1=h69220b7_0
  - libxml2=2.13.8=hfdd30dd_0
  - lz4-c=1.9.4=h6a678d5_1
  - matplotlib=3.10.0=py312h06a4308_0
  - matplotlib-base=3.10.0=py312hbfdbfaf_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py312h5eee18b_2
  - mkl_fft=1.3.11=py312h5eee18b_0
  - mkl_random=1.2.8=py312h526ad5a_0
  - mysql=8.4.0=h721767e_2
  - ncurses=6.4=h6a678d5_0
  - numpy=2.0.1=py312hc5e2394_1
  - numpy-base=2.0.1=py312h0da6c21_1
  - nvidia-ml-py=12.535.133=py312h06a4308_0
  - openjpeg=2.5.2=h0d4d230_1
  - openldap=2.6.4=h42fbc30_0
  - openssl=3.0.16=h5eee18b_0
  - pcre2=10.42=hebb0a14_1
  - pip=25.1=pyhc872135_2
  - psutil=5.9.0=py312h5eee18b_1
  - pthread-stubs=0.3=h0ce48e5_1
  - pyparsing=3.2.0=py312h06a4308_0
  - pyqt=6.7.1=py312h6a678d5_1
  - pyqt6-sip=13.9.1=py312h5eee18b_1
  - python=3.12.11=h22baa00_0
  - python-dateutil=2.9.0post0=py312h06a4308_2
  - pytorch-cuda=11.8=h7e8668a_6
  - qtbase=6.7.3=hdaa5aa8_0
  - qtdeclarative=6.7.3=h6a678d5_0
  - qtsvg=6.7.3=he621ea3_0
  - qttools=6.7.3=h80c7b02_0
  - qtwebchannel=6.7.3=h6a678d5_0
  - qtwebsockets=6.7.3=h6a678d5_0
  - readline=8.2=h5eee18b_0
  - scikit-learn=1.6.1=py312h6a678d5_0
  - scipy=1.15.3=py312h525edd1_0
  - setuptools=78.1.1=py312h06a4308_0
  - sip=6.10.0=py312h6a678d5_0
  - six=1.17.0=py312h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tbb=2021.8.0=hdb19cb5_0
  - threadpoolctl=3.5.0=py312he106c6f_0
  - tk=8.6.14=h993c535_1
  - tmux=3.3a=h5eee18b_1
  - tornado=6.5.1=py312h5eee18b_0
  - tqdm=4.67.1=py312he106c6f_0
  - tzdata=2025b=h04d1e81_0
  - unicodedata2=15.1.0=py312h5eee18b_1
  - wcwidth=0.2.13=py312h06a4308_0
  - wheel=0.45.1=py312h06a4308_0
  - xcb-util=0.4.1=h5eee18b_2
  - xcb-util-cursor=0.1.5=h5eee18b_0
  - xcb-util-image=0.4.0=h5eee18b_2
  - xcb-util-renderutil=0.3.10=h5eee18b_0
  - xkeyboard-config=2.44=h5eee18b_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - annotated-types==0.7.0
      - anyio==4.9.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - async-lru==2.0.5
      - attrs==25.3.0
      - babel==2.17.0
      - beautifulsoup4==4.13.4
      - bleach==6.2.0
      - certifi==2025.6.15
      - cffi==1.17.1
      - charset-normalizer==3.4.2
      - click==8.2.1
      - comm==0.2.2
      - debugpy==1.8.14
      - decorator==5.2.1
      - defusedxml==0.7.1
      - executing==2.2.0
      - fastjsonschema==2.21.1
      - filelock==3.13.1
      - fqdn==1.5.1
      - fsspec==2024.6.1
      - gitdb==4.0.12
      - gitpython==3.1.44
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.10
      - ipykernel==6.29.5
      - ipython==9.4.0
      - ipython-pygments-lexers==1.1.1
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.4
      - json5==0.12.0
      - jsonpointer==3.0.0
      - jsonschema==4.24.0
      - jsonschema-specifications==2025.4.1
      - jupyter-client==8.6.3
      - jupyter-core==5.8.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.16.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.4
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - markupsafe==2.1.5
      - matplotlib-inline==0.1.7
      - mistune==3.1.3
      - mpmath==1.3.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.3
      - notebook==7.4.4
      - notebook-shim==0.2.4
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-nccl-cu11==2.21.5
      - nvidia-nvtx-cu11==11.8.86
      - overrides==7.7.0
      - packaging==25.0
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==11.0.0
      - platformdirs==4.3.8
      - prometheus-client==0.22.1
      - prompt-toolkit==3.0.51
      - protobuf==6.31.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycparser==2.22
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pygments==2.19.2
      - python-json-logger==3.3.0
      - pyyaml==6.0.2
      - pyzmq==27.0.0
      - referencing==0.36.2
      - requests==2.32.4
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.26.0
      - send2trash==1.8.3
      - sentry-sdk==2.32.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.7
      - stack-data==0.6.3
      - sympy==1.13.1
      - terminado==0.18.1
      - tinycss2==1.4.0
      - torch==2.6.0+cu118
      - torchaudio==2.6.0+cu118
      - torchvision==0.21.0+cu118
      - traitlets==5.14.3
      - triton==3.2.0
      - types-python-dateutil==2.9.0.20250516
      - typing-extensions==4.12.2
      - typing-inspection==0.4.1
      - uri-template==1.3.0
      - urllib3==2.5.0
      - wandb==0.21.0
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
prefix: /home/faeyza/miniconda3/envs/SimpleTTA
